CREATE TABLE IF NOT EXISTS STV2024021942__DWH.S_AUTH_HISTORY 
(
    HK_L_USER_GROUP_ACTIVITY BIGINT NOT NULL CONSTRAINT FK_S_AUTH_HISTORY_L_USER_GROUP_ACTIVITY REFERENCES STV2024021942__DWH.L_USER_GROUP_ACTIVITY (HK_L_USER_GROUP_ACTIVITY),
    USER_ID_FROM INT,
    EVENT VARCHAR(10),
    EVENT_DT DATETIME,
    LOAD_DT DATETIME,
    LOAD_SRC VARCHAR(20)
)
ORDER BY LOAD_DT
SEGMENTED BY HK_L_USER_GROUP_ACTIVITY ALL NODES
PARTITION BY LOAD_DT::DATE
GROUP BY CALENDAR_HIERARCHY_DAY(LOAD_DT::DATE, 3, 2);