CREATE TABLE IF NOT EXISTS STV2024021942__STAGING.GROUP_LOG
(
    GROUP_ID INT,
    USER_ID INT,
    USER_ID_FROM INT, 
    EVENT VARCHAR(10),
    EVENT_DTTM DATETIME
)
ORDER BY DATETIME
SEGMENTED BY HASH(GROUP_ID) ALL NODES
;
