INSERT INTO STV2024021942__DWH.L_USER_GROUP_ACTIVITY(HK_L_USER_GROUP_ACTIVITY,HK_USER_ID,HK_GROUP_ID,LOAD_DT,LOAD_SRC)
WITH USERS AS
(
    SELECT
        DISTINCT GL.GROUP_ID,
        GL.USER_ID,
        HU.HK_USER_ID,
        HG.HK_GROUP_ID 
    FROM STV2024021942__STAGING.GROUP_LOG GL 
    INNER JOIN STV2024021942__DWH.H_USERS HU ON GL.USER_ID = HU.USER_ID
    INNER JOIN STV2024021942__DWH.H_GROUPS HG ON GL.GROUP_ID = HG.GROUP_ID
)
SELECT 
    HASH(HK_GROUP_ID, HK_USER_ID) AS HK_L_USER_GROUP_ACTIVITY,
    HK_USER_ID,
    HK_GROUP_ID,
    NOW() AS LOAD_DT,
    'S3' AS LOAD_SRC
FROM USERS 
;